import os
import json
import shutil
from fastapi import FastAPI, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pptx import Presentation
from pptx.util import Pt
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=OPENROUTER_API_KEY,
)

def create_pptx(slides_data, output_path):
    prs = Presentation()
    
    # Create title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = slides_data.get("title", "Lesson Presentation")
    subtitle.text = "Generated by AI"
    
    # Enforce formatting for title slide
    for shape in slide.shapes:
        if not shape.has_text_frame:
            continue
        for paragraph in shape.text_frame.paragraphs:
            for run in paragraph.runs:
                run.font.name = 'Comic Sans MS'
                run.font.size = Pt(36)

    # Add content slides
    bullet_slide_layout = prs.slide_layouts[1]
    for slide_info in slides_data.get("slides", []):
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = slide_info.get("title", "")
        
        tf = body_shape.text_frame
        tf.text = slide_info.get("content", "")
        
        # Enforce Comic Sans 36pt constraint on content slides
        for shape in slide.shapes:
            if not shape.has_text_frame:
                continue
            for paragraph in shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.name = 'Comic Sans MS'
                    run.font.size = Pt(36)
                    
    prs.save(output_path)
    
@app.post("/generate-presentation")
async def generate_presentation(
    file: UploadFile = File(None),
    gradeLevel: str = Form(...),
    categories: str = Form(...),
    objectives: str = Form(...),
    interactive: bool = Form(...)
):
    upload_dir = "uploads"
    os.makedirs(upload_dir, exist_ok=True)
    
    # 1. Save uploaded file if any
    if file and file.filename:
        file_location = os.path.join(upload_dir, file.filename)
        with open(file_location, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
    
    # 2. Construct AI Prompt
    prompt = f"""
    You are an expert teacher creating a highly engaging lesson presentation.
    Grade Level: {gradeLevel}
    Categories: {categories}
    Objectives: {objectives}
    Include Interactive Games: {interactive}
    
    Create an outline for a PowerPoint presentation. The font will be very large (36pt), so keep the text on each slide extremely brief (max 3 bullet points per slide).
    
    Return ONLY a valid JSON object in this exact format, with no markdown formatting:
    {{
      "title": "Main Presentation Title",
      "slides": [
        {{ "title": "Slide 1 Title", "content": "Bullet point 1\\nBullet point 2" }},
        {{ "title": "Slide 2 Title", "content": "Bullet point 1\\nBullet point 2" }}
      ]
    }}
    """

    print("Calling OpenRouter AI via OpenAI SDK...")
    try:
        completion = client.chat.completions.create(
            model="meta-llama/llama-3.1-8b-instruct:free",
            messages=[{"role":"user","content":prompt}]
        )
        ai_response = completion.choices[0].message.content
        # Ensure it's clean JSON
        ai_response = ai_response.replace("```json", "").replace("```", "").strip()
        slides_data = json.loads(ai_response)
    except Exception as e:
        print("Failed to generate or parse AI output:", e)
        slides_data = {
            "title": "Error generating lesson",
            "slides": [
                {"title": "Error", "content": f"Failed to parse AI response.\\n{str(e)}"}
            ]
        }
    
    # 3. Generate PPTX file
    output_filename = "AI_Lesson_Plan.pptx"
    output_path = os.path.join(upload_dir, output_filename)
    
    create_pptx(slides_data, output_path)
    
    # 4. Return file to the frontend
    return FileResponse(
        output_path, 
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", 
        filename=output_filename
    )

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
